### ISSUE TITLE
container won't work on kubernetes 1.3.5 (docker 1.11.2 build b9f10c9)

### ISSUE THREAD

**Issue by adiri** [pires/docker-elasticsearch-kubernetes#17]
Heya all,

I'm trying to run ES master on my k8s cluster (hosted on AWS) and getting an error:

```
admin@ip-172-20-55-229:~$ kubectl logs es-master-2201531720-neui0
[2016-09-03 05:46:00,466][INFO ][node                     ] [Darkstar] version[2.3.4], pid[11], build[e455fd0/2016-06-30T11:24:31Z]
[2016-09-03 05:46:00,467][INFO ][node                     ] [Darkstar] initializing ...
[2016-09-03 05:46:01,235][INFO ][plugins                  ] [Darkstar] modules [reindex, lang-expression, lang-groovy], plugins [cloud-kubernetes], sites []
[2016-09-03 05:46:01,267][INFO ][env                      ] [Darkstar] using [1] data paths, mounts [[/data (/dev/xvdbe)]], net usable_space [46.5gb], net total_space [49gb], spins? [no], types [ext4]
[2016-09-03 05:46:01,267][INFO ][env                      ] [Darkstar] heap size [247.5mb], compressed ordinary object pointers [true]
[2016-09-03 05:46:03,890][INFO ][node                     ] [Darkstar] initialized
[2016-09-03 05:46:03,898][INFO ][node                     ] [Darkstar] starting ...
Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:186)
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:233)
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:209)
	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:122)
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:424)
	at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:321)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:278)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**Comment by adiri** [comment]
Also happen on 2.3.5_1...

**Comment by adiri** [comment]
error

**Comment by timchenxiaoyu** [comment]
how to solve?

**Comment by thuandt** [comment]
I think your node seem don't have `k8s private interface`

**Comment by slmingol** [comment]
This is the line that's the issue: `Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]`. Try explicitly setting the `network.host: [ ... ]` in the elasticsearch.yml file.

**Comment by timchenxiaoyu** [comment]
I change to unicast ,and solve it
