### ISSUE TITLE
Permissions erros installing plugins

### ISSUE THREAD

**Issue by andrewmclagan** [pires/docker-elasticsearch-kubernetes#34]
The base user `elasticsearch` does not have the required permissions to install the `s3-repository` plugin.

````
sh: error setting limit: Operation not permitted
elasticsearch.yml  jvm.options        log4j2.properties
-> Downloading repository-s3 from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.FileSystemException: /elasticsearch/config/repository-s3: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setOwners(UnixFileAttributeViews.java:252)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setGroup(UnixFileAttributeViews.java:291)
	at org.elasticsearch.plugins.InstallPluginCommand.setOwnerGroup(InstallPluginCommand.java:596)
	at org.elasticsearch.plugins.InstallPluginCommand.installConfig(InstallPluginCommand.java:569)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:495)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
````

we were running that with the command

`yes | sudo -E -u elasticsearch /elasticsearch/bin/elasticsearch-plugin install repository-s3`

it does work with the root container user:

`yes | /elasticsearch/bin/elasticsearch-plugin install repository-s3`

**Comment by pires** [comment]
Are you running this on a running container?

[The runnable script is setting the needed permissions](https://github.com/pires/docker-elasticsearch/blob/master/run.sh#L7).

**Comment by andrewmclagan** [comment]
No as a derived container with a new `run.sh` having only slight modifications:

````bash
#!/bin/sh

# provision elasticsearch user
addgroup sudo
adduser -D -g '' elasticsearch
adduser elasticsearch sudo
chown -R elasticsearch /elasticsearch /data
echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# allow for memlock
ulimit -l unlimited

ls /elasticsearch/config

# install plugin
yes | /elasticsearch/bin/elasticsearch-plugin install repository-s3

# run
sudo -E -u elasticsearch /elasticsearch/bin/elasticsearch
````

It works as above, just thought id mention the issue?

**Comment by pires** [comment]
Use a different approach with image `5.2.2_2`:

ENV ES_PLUGINS_INSTALL="repository-s3"
