### ISSUE TITLE
failed to resolve host [elasticsearch-discovery]

### ISSUE THREAD

**Issue by Fantomatic** [pires/docker-elasticsearch-kubernetes#35]
Hello, 
I'm using something similar to https://github.com/exoscale/multi-master-kubernetes for creating my cluster on some servers based on RHEL7 ( not the atomic host version ). 
I've tried with or without discovery plugin ( depending on my version of elasticsearch ), and i found your implementation through dns. My problem when i try it, is ( like always for me ) the discovery which seem to not be able to resolve. 
It loop with : 

`[2017-02-14T13:25:51,406][WARN ][o.e.d.z.UnicastZenPing   ] [LX8rjyK] failed to resolve host [elasticsearch-discovery]
java.net.UnknownHostException: elasticsearch-discovery
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_111]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_111]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_111]
        at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:857) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:812) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:657) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[2017-02-14T13:25:59,408][WARN ][o.e.d.z.UnicastZenPing   ] [LX8rjyK] timed out after [5s] resolving host [elasticsearch-discovery]`

I also have this has logs of my kube-dns which might be causing problem : 
` server.go:155] Starting SkyDNS server (0.0.0.0:10053)
server.go:165] Skydns metrics enabled (/metrics:10055)
logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
sync.go:105] Error getting ConfigMap kube-system:kube-dns err: configmaps "kube-dns" not found
dns.go:190] Error getting initial ConfigMap: configmaps "kube-dns" not found, starting with default values
server.go:126] Setting up Healthz Handler (/readiness)
server.go:131] Setting up cache handler (/cache)
server.go:120] Status HTTP port 8081`

I hope you will be able to give me a hint, i've spent a lot's of time in this discovery problem !

**Comment by Fantomatic** [comment]
little update : my probleme seem to come from my dns. I did the test recommanded by https://kubernetes.io/docs/admin/dns/ 
Failed and got nslookup: can't resolve 'kubernetes.default'. But all their possible solutions is not mine sadly.

**Comment by pires** [comment]
Yes, it's a DNS problem.

**Comment by Fantomatic** [comment]
The controller logs doesn't ring any bell for you ?  I can't change the hostnames sadly.

**Comment by pires** [comment]
It's something related to your Kubernetes cluster set-up, not Elasticsearch or this image, I'm sorry to say.

**Comment by mtaylor769** [comment]
I am also getting this problem on a bare-metal install using kubeadm and 5 physical nodes. It worked at one time then, the cluster was destroyed and when I rebuilt it, it is only the es-client nodes that are throwing this error (es 6.0.0) any new info on what may be causing this?
