### ISSUE TITLE
Got exception when start up

### ISSUE THREAD

**Issue by ddyycao** [pires/docker-elasticsearch-kubernetes#5]
I'm runing kubernetes1.2 on centos7

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
level=info msg="Starting go-dnsmasq server 0.9.8 ..." 
level=info msg="Search domains in use: [default.svc.cluster.local. svc.cluster.local. cluster.local.]" 
level=info msg="Ready for queries on tcp://127.0.0.1:53 - Nameservers: [10.254.210.250:53 10.45.8.11:53]" 
level=info msg="Ready for queries on udp://127.0.0.1:53 - Nameservers: [10.254.210.250:53 10.45.8.11:53]" 
[services.d] done.
[2016-03-28 09:24:55,025][INFO ][node                     ] [Saint Anna] version[2.2.1], pid[171], build[d045fc2/2016-03-09T09:38:54Z]
[2016-03-28 09:24:55,026][INFO ][node                     ] [Saint Anna] initializing ...
[2016-03-28 09:24:55,495][INFO ][plugins                  ] [Saint Anna] modules [lang-expression, lang-groovy], plugins [cloud-kubernetes], sites []
[2016-03-28 09:24:55,513][INFO ][env                      ] [Saint Anna] using [1] data paths, mounts [[/data (/dev/mapper/rhel-root)]], net usable_space [19.4gb], net total_space [40gb], spins? [possibly], types [xfs]
[2016-03-28 09:24:55,513][INFO ][env                      ] [Saint Anna] heap size [1007.3mb], compressed ordinary object pointers [true]
[2016-03-28 09:24:57,340][INFO ][node                     ] [Saint Anna] initialized
[2016-03-28 09:24:57,340][INFO ][node                     ] [Saint Anna] starting ...
Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
        at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:186)
        at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:233)
        at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:209)
        at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:122)
        at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:424)
        at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:321)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.node.Node.start(Node.java:252)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:221)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:287)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
[2016-03-28 09:24:57,421][INFO ][node                     ] [Saint Anna] stopping ...
[2016-03-28 09:24:57,433][INFO ][node                     ] [Saint Anna] stopped
[2016-03-28 09:24:57,433][INFO ][node                     ] [Saint Anna] closing ...
[2016-03-28 09:24:57,441][INFO ][node                     ] [Saint Anna] closed
/run.sh exited 1
level=info msg="Application exit requested by signal: terminated" 
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by pires** [comment]
>  No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]

You can try and change your own version of `elasticsearch.yml` and change [the `network.host` flag](https://github.com/pires/docker-elasticsearch-kubernetes/blob/master/elasticsearch.yml#L8).

**Comment by ddyycao** [comment]
Thanks!  I check the offical es image and use "network.host:0.0.0.0" this fix the problem

**Comment by selvakn** [comment]
With pull request #6, `network.host` can be easily changed, without building a new image.
